## Psychological Outcomes \label{psych} {#sec-psych}

Depression, anxiety, and burnout are selected as outcomes of interest due to
the relatedness between burnout $\rightleftharpoons$ depression and burnout
$\rightleftharpoons$ anxiety [@koutsimani2019relationship]. The partial
correlations have a moderate effect size, signifying the boundary between
burnout and depression also burnout and anxiety. Therefore, statistically,
each of depression, anxiety, and burnout does not share similar latent
construct even though they have closely-related manifests. This is
interpretable as distinctive remarks to differentiate three of such outcomes
and the clinical importance of examining the others when one is present.

Burnout is a condition of increasing depersonalization and emotional
exhaustion, leading to reduced personal accomplishment in the workplace (sense
of inefficacy). Burnout often happens due to a long-term ongoing stressor,
where the inability to cope with external issues decreases work engagement
[@Schaufeli2017]. The incidence of burnout overlaps with psychological
distress, marked by depressive symptoms or anxiety.

In a recent finding, burnout is partially explainable by depression and
anxiety. Depression symptoms pose similar characteristics to exhaustion and
depersonalization, while anxiety is related to the sense of personal inefficacy
[@golonka2019occupational]. In theory, depression is marked by the loss of
energy (fatigue) and anxiety is marked by being excessively worried; but a
study suggested the presence of anxious depression [@gaspersz2018patients],
which in turn also implies a pathophysiological overlap between depression and
anxiety.  Moreover, lower brain connectivity in the default mode network is a
curious co-occurrence between depression [@jacob2020neural], anxiety
[@imperatori2019default], and burnout [@shang2022aberrant]. Neurobiological,
clinical, and contextual overlaps between depression, anxiety, and burnout
necessitate the inclusion of these outcomes to infer a more general impact of
associated stressors.

Several policies have been implemented to alleviate the mental health burden in
Indonesia, mainly highlighted in the Mental Health Act in 2014
[@tampubolon2021covid], and further defined in the Indonesian Minister of
Health Regulation Number 77 of 2015 and Indonesian Minister of Health
Regulation Number 54 of 2017 [@hartono2018tracking]. During the pandemic, the
government of Indonesia has stipulated a Presidential Decree R1 No. 7 of 2020
to promptly respond the pandemic; however, the practical implementation has not
addressed mental health issues. Though, several ongoing initiatives led by the
government has been realized as a regulation on managing a digital counselling
platform [@tampubolon2021covid]. The digital platform, conducted through
various chat-based and video call-based application, helps the general
population to get in touch with therapists, psychologists, counselors, and
educational practitioners [@ifdil2020online]. Tele-consulting, either through
chat or video call, enables practitioners to provide psychological first aid to
address elevated distress during the pandemic, depression, and anxiety
[@ifdil2020online].

