## Stressors Precipitating the Development of Mental Issues \label{stressor} {#sec-stressor}

Resilience is the moderator between risk factors and psychological disorders,
therefore, a clear definition of included stressors will aid in developing an
explainable and generalizable study design [@ungar2020resilience]. Defining the
stressors also allow us to measure resilience using a reactivity approach,
where resilience is evaluated as growing tolerance to regular stress
[@davydov2010resilience]. This way we can partly assess the dynamic process in
developing an adaptive behavior.

The presence of stressors disrupts physiological function to a lower utility
state [@oken2015systems]. Following the methods proposed by @veer2021psycho,
our research evaluates two distinct groups of stressor, namely the general
daily stressor and health-related stressor. The general stressor is an
instrument comprising ten items of daily hassles and life events, while the
health-related stressor consists of items reflecting adversity related to
general health concern in self, families, and close relatives. Any item rated
as `"TRUE"` is then weighted for the severity, ranging from *not burdensome* (0) to
*substantially burdensome* (5). Below is the excerpt of the general stressor
items:

- Negative political events
- Conflicts with relatives or colleagues
- Financial problems
- Physical health problems
- Mental health problems
- Burdensome experiences with family
- Burdensome experiences in workplace
- Conflicts with strangers
- Separation from a loved one, which triggers reduced social contact and
  loneliness
- Death of a loved one

The health-related stressor in @veer2021psycho was particularly narrating
distress caused by the COVID-19 pandemic. In brief, these items are comprised
of trepidation or perceived burden due to a disease, thus adaptable for a more
general research context.

