---
format:
  gfm:
    output-file: README.md
  revealjs:
    smaller: true
    scrollable: true
---

## 2024-05-23

- 9-mo interview form is in Prof. Frederike, I will receive it after she signed it
- Prof. Talitha will email Prof. Ralph about the DD program
- Prof. Frederike will follow up on the lunch meeting ICPE
- IADB data analysis:
  - Talk with Jens on how to remove the data with DDD outliers
  - One option is to remove based on the period of use
  - Change the table header: It's not weighted DDD, it's a weight to generate edges
  - As a follow up: Prof. Talitha will contact a pharmacist to further discuss our finding on eigenvector centrality

## 2024-05-14

- Descriptive findings of IADB:
  - Distribution of DDD for each medication
  - Tabular description of the data 
- Inform Fang so that I can present my work on the 5th of June
- Move the biweekly meeting to 13th of June
- Prepare a slide for PEGET meeting $\to$ 20 minutes per presenter

## 2024-04-29

- Remove action points from the revised TSP $\to$ Include the project definition into TSP
  - Chapter 1: Still some rooms for revision, need to work on comments in the document later
  - Chapter 2: Revise the draft
  - Chapter 3: Make sure that this is connected with chapter 2
  - Chapter 4: Outside of Prof. Talitha's expertise, need a co-author who knows a bit more on this concept (especially LDI, and MINI)
    - Check Lifelines Wiki
    - Check literatures using LDI and MINI
  - Chapter 5: Narrow down the scope to universal mental health promotion program in workplace
    - Check the literatures on Dutch and international
    - Make sure that the model is transferrable
- Revise the TSP and include the project definition as an appendix:
  - Edit the timeline: include preparation, execution, and reporting phases
    - Y1 and Y2: detailed per quarter
    - Y3 and Y4: detailed per semester
  - Remove plan on survey
  - Add chapter plans
- Work on the interpretation of findings
  - Less jargon, more verbose concept
  - Always include an introduction
  - Focus on the research question and answer it
- Decide the journal for IADB manuscript $\to$ Involve Spyros for this manuscript
- For each chapter, decide who to involve and when to involve them
- Involve Prof. Mako from the start for the 1st and 4th chapters
- Involve Prof. Frederike more in the scoping review

## 2024-04-24

- Contact Prof. Mako for a bimonthly meeting
- Fill in and send the 9-mo interview form $\to$ Send it by EOW 
- Submit the IADB abstract to EUPHA and ISPOR
- RIVM research group will attend EUHEA as well $\to$ Networking with Hanneke to talk about resilience
- Weighting method when creating a DPN:
  - Dividing and normalizing (what I did)
  - Multiply by dose
  - Multiply by dose then log
- Lunch meeting with Prof. Frederike's group on Tuesday $\to$ Many talks about dynamic model in psychiatry
- Ask Steef about who might be involved in dynamic model in psychiatry

## 2024-04-15

- Chapter 1:
  - The topic is too broad
  - Need to include someone with an expertise on resilience
  - Reformulate the research question to be more narrow: "How does resilience work as a moderator in relation with stressors and mental disorders?"
  - In project scope, explain that neurobiological/physiological mechanistic explanation is not a part of the review  
  - In activity plan: Contact collaborators sooner
  - Action point: Make the question simpler, contact the librarian, create an inclusion based on model for chapter 5
- Chapter 2: Involve Spyros for this chapter
- Chapter 3: Narrow down the objective to evaluate psychopharmaca uses of anxiolytics and antidepressants
- Chapter 4:
  - We need someone with an expertise in psychological resilience
  - Signifies how this chapter is required for modelling
- Chapter 5:
  - Limit the scenario to universal intervention
  - Focus the intervention to workplace-based
  - Send the paper on about resilience
  - State that we only focus on depression and anxiety part of MINI using Lifelines data

## 2024-03-29

- Send the initial draft before the 3^rd^ of April
- Send the ABM papers to Prof. Talitha
- Read more about the international guideline on polypharmacy
- To learn in project management course $\to$ Delegating task and collaborating with others

## 2024-03-25

- Three courses of action upon the 9-mo interview:
  - Plan A: Re-align the research purpose, go with the current supervisory team
  - Plan B: Find another suitable supervisor
  - Plan C: Terminate studentship
- Course on science communication
- Start the introductory essay by explaining ABM, limit to 3,000 words
- Write with less jargon 

## 2024-03-22

- Scoping review:
  - Look a little bit into resilience, find some general review on resilience and formulate a question on this
    - Make a clear inclusion and exclusion criteria
    - Create a working definition of resilience → Done, write it explicitly
    - Check if the body of evidence is sufficient → Do it for plan B as well
    - Find a co-author with expertise on state resilience
 - Plan B: Scoping review on the measurement of resilience
- Concurrent psychopharmaca uses: Send a draft of introduction + methods, deadline on the 19^th^ of April  
- Trend of psychopharmaca uses:
  - Formulate the questions better → Why do we need to monitor it this way?
  - What is the societal problem to solve here?
  - Example: The danger of polypharmacy
  - **Other idea:** Look at the duration of use → Read more literature on this
- Lifelines study: Research question $\to$ How applicable is the residual method of measuring resilience?
- ABM: Publish the model-building procedure

## 2024-03-21

- Having a discussion with Hanneke from RIVM $\to$ PI for youth model on mental health
- Research group in Rotterdam using a group-based model
- Conceptual framework:
  - Simplify the outcome to only include depression
  - Give a rationale why medication can influence resilience
- IADB analysis:
  - Create a summary descriptive analysis for the original IADB dataset
  - Measure time of follow up for each person
  - Eigenvector centrality: Sort out pattern of co-prescription systematically
  - For discussion section: Compare with other papers evaluating co-prescriptions
- Explain and discuss the plan for the chapter outlines $\to$ Then explain how they are connected
- Think about the author team
- It takes about 8 month to prepare a data request for Lifelines $\to$ Consult Taichi on this

## 2024-03-15

- IADB analysis:
  - Make a simulation to assess which weighting method suits the dataset $\to$ Per discussion with Spyros:
    - Baseline: Unregularized matrix of number of claims
    - Weight 1: $\frac{1}{k} \left( \frac{n_i}{DDD_i} + \frac{n_j}{DDD_j} \right); k \in \{1, ..., 9\}$
    - Weight 2: $\frac{1}{k} \left( \frac{n_i + n_j}{DDD_i + DDD_j} \right); k \in \{1, ..., 9\}$
  - Continue the analysis plan:
    - Find the best-fitting model for each series
    - Conduct an interrupted time-series analysis
    - Fit a VAR model for eigenvector centrality and the number of claim
  - Consider fitting an exponential random graph model to temporal graphs of co-medication
- Prepare the document for the 9-month interview
- Recheck the TSP and review the thesis component
- Determine how to outline the thesis

## 2024-03-13

- Discussion with Prof. Eelko:
  - Ensure that the query is well controlled $\to$ No growing/shrinking population
  - The data should reflect a static cohort from 2018 to 2022
  - Subset the patient to only include DDD = 1
- Need to think more about why regularize against DDD

## 2024-03-07

- Discussion with Prof. Frederike:
  - Prepare a slide outlining my plan
  - Use some parts from proposal presentation
  - Emphasize how these projects will go inline
  - Main goal: Implementing ABM to measure the cost-effectiveness of public health policy related to mental resilience
- Survey:
  - Further correspondence
- ISPOR: Think more about what to achieve in two years
- ABM:
  - Check out courses on health economics $\to$ Usually starts in Autumn
  - Mastricht/Rotterdam might have a course on modelling with R $\to$ Contact Jinjing Fu

## 2024-03-05

- Visit https://brightspace.rug.nl/ to access learning materials
- Questions to ask to students:
  - How do you calculate the cost?
  - What does the histogram imply?
- Scoring:
  - Prof. Talitha will send an example of well-written report
  - Score the essay using a rubrik/standardized grading form
- Every group will handle two excel files for QALY and pain score

## 2024-02-29

- Produce diagnostic plot of eigentriple plot from SSA
- Schedule a meeting with Prof. Frederike
- Prepare a short slide containing:
  - Updated research questions
  - Brief on methods
  - Diagnostic plots
  - Preliminary results
- Check out TRIMBOS NEMESIS $\to$ They use CIDI in Netherlands

## 2024-02-16

- Add weekly aggregate of sociodemographic data as a covariate when performing further modelling, discuss it with Jens:
  - Age
  - Sex (ratio of male:female)
- Draft a analytic plan for modelling:
  - Model selection phase
  - Interrupted time series analysis
  - Vector autoregression between eigenvector centrality and number of claims
- Allocate at least one day to revisit the draft on umbrella review
- Plan a meeting with Jens and Prof. Frederike

## 2024-02-09

- Umbrella review:
  - Need to add explanation on the methods
  - Add a section on data analysis
  - Elaborate how to explain the data
  - Check out on the risk of bias (Egger's test) $\to$ Consider to remove it
  - Add line of expected prevalence to the figure
- Medication trend:
  - Add the method section and elaborate in full extend what I did
  - Sent the report summary to Jens and Frederike

## 2024-01-31

- Plan a regular meeting with Prof. Frederike, preferably biweekly $\to$ Joint meeting with Prof. Talitha
- Communicate results in a general context, avoid technical jargon if possible
- Keep the main objectives in check
- Consult to experts before submitting a paper
- Ask Taichi about pint of science
- Find about science communication at https://europa.eu/

## 2024-01-26

- Consider using policies/events during COVID-19 pandemic as exogenous regressors
- Contact people from Econometrics and Operations Research group
- Have a discussion with Irene

## 2024-01-19

- Ask the secretary (Vicky) for the UMCG card
- Reschedule the 6-mo interview with Prof. Frederike and Prof. Talitha
- Share link about Git course to Prof. Talitha
- Discuss about time-series analysis with other PhD students/Post-docs
- Dutch's PhD conference in mental health

## 2024-01-15

- Preparation for 6-mo interview
- Suggestions from the presentation:
  - Definition on resilience is important, keep it that way
  - Use only conceptual framework for RUG intro essay, no need for theoretical framework
  - Describe a bit about medication use in mental health issue, e.g. how it impacts resilience
- When planning the survey:
  - Consult to Prof. Mirra and Prof. Frederike
  - Need: Face validity, pilot study, dissemination
  - Plan for the proposal defense by the EOY
  - Include more variables relevant to ABM
  - Set the deadline when the ethical clearance should be submitted
- Scoping review:
  - Expedite the bibliometrix analysis
  - Start searching and reading
- IADB analyis: Should be finished by the EOM in April
- Conferences to check:
  - IHEA: https://healtheconomics.org/events
  - InaHTA
  - EuroHEA
  - ISPOR
  - HTEA
  - SMDM

## 2023-12-14

- Prof. Talitha will join the pre-proposal defense on the 20th of December 2023
- Input for proposal:
  - Will be commented on Saturday
  - Figures: Clarify how medication affect resilience
- IADB TS:
  - Use monthly data to evaluate periodicity
  - Explore periodicity in first-order differenced data

## 2023-12-07

- Split dataset into training and testing
- Evaluate metrics based on https://stats.stackexchange.com/a/418386
  - Mean Error, Mean Absolute Error, Root Mean Squared Error
  - Mean Percentage Error, Mean Absolute Percentage Error, Mean Absolute Scaled Error
  - Autocorrelation of errors at lag 1
- Check literatures on time-series analysis for medication claim/prescription data
- Ask Stijn about temporal network analysis
- Make a different descriptive plot:
  - Y axis: Metrics
  - X axis: Jan - Dec
  - Color: Year
  - Circular histogram plot for each year

## 2023-12-01

- IADB medication claim time-series analysis:
  - Hypothesis: High eigenvector centrality in medication with low claim
  - Need people familiar with time-series analysis as a co-author
  - Create a circular histogram
  - Email Guiling to confirm her findings
  - Use causal inference method to get counterfactual trend
  - Find diagnostic measures
  - Network analysis:
    - Find methods to evaluate network evolution
    - Do a subset analysis on psychopharmaca
- Contact the principal investigator from SEARO WMH Consortium
- Complete the six-month interview document and send it to Prof. Talitha

## 2023-11-23

- See the decomposition per claim and per patient as well
- For time-series analysis, we will need other people knowledgeable in this field to check on our data $\to$ Check with Sumayra
- Contact Hao to plan a meeting on discussing ISPOR student chapter RUG

## 2023-11-20

- Survey $\to$ Involve dr. Fidiansyah
- Proposal should be submitted before December
- Proposal defense:
  - Prof. Mako
  - Prof. Talitha
  - dr. Irmansyah
  - dr. Nugroho Harry Santoso
  - Pak Yahya Umar
  - Prof. Besral
- Add a qualitative approach in methods:
  - FGD: 8-12 people per group $\to$ Number of groups depends on the demography
  - Semi-structured in-depth interview with community leaders

## 2023-11-16

- Will have a meeting with Prof. Mako on Sunday: Discuss the possibility of connecting with dr. Irmansyah
- Business generator team in RUG: https://www.businessgeneratorgroningen.com/
- ISPOR student chapter $\to$ It's possible to do it in RUG
- Prepare for next week:
  - Data management plan $\to$ Check the template in RUG's website: https://www.rug.nl/research/grip/research/griprdmp
  - Checklist for 6-month meeting

## 2023-11-09

- Bibliometrics analysis and scoping review:
  - Continue on reading about the Bradford's law and Lotka's coefficient
  - Determine how bibliometrics analysis can help the scoping review
  - Communicate with the librarian on how to perform search for scoping review
- Discuss with Prof. Mako:
  - How to get it touch with dr. Firmansyah, or potentially with the MoH
  - What to report during the bimonthly meeting

## 2023-10-26

- Double-doctorate programme:
  - Confirm to dr. Indri when the MOU between RUG and UI will end
  - Send full contact information to Prof. Talitha
- Ask: Access to World Mental Health survey data and CIDI results
  - CIDI: https://medicine.yale.edu/intmed/vacs/instruments/cidi_lifetime_paper_version_who-1_3299_284_639_v1.pdf
  - Netherlands participation via ESEMeD (https://www.hcp.med.harvard.edu/wmh/participating_collaborators.php):
    - Peter de Jonge, PhD - Principal Investigator, University Medical Center Groningen, Netherlands
    - Margreet ten Have, PhD - Principal Investigator, Netherlands Institute of Mental Health and Addiction (Trimbos Institute)
    - Pim Cuijpers, PhD, Vrije Universiteit Amsterdam, Netherlands
    - Johan Ormel, PhD, University of Groningen, Netherlands
    - Ron de Graaf, PhD, Netherlands Institute of Mental Health and Addiction (Trimbos Institute)
  - Advantages of conducting WMH survey: https://www.cambridge.org/core/services/aop-cambridge-core/content/view/3E80691DB1C878C85779756486267C56/S1121189X00004395a.pdf/the-world-health-organization-world-mental-health-survey-initiative.pdf
  - Further contact:
    - South East Asia Regional Office (SEARO)
      - William G. Axinn, PhD - Principal Investigator, University of Michigan
      - Dirgha Ghimire, PhD - Principal Investigator, University of Michigan
    - Western Pacific Regional Office (WPRO) $\to$ Regional coordinator: Kate Scott, PhD, University of Otago, Dunedin, New Zealand
  - US National Comorbidity Survey (NCS) data access: https://www.hcp.med.harvard.edu/ncs/ncs_data.php
- Meeting preparation:
  - Contact dr. Frederike about the plan of joining WHO WMH survey

## 2023-10-19

- Umbrella review:
  - Intended message: Raising awareness of depression in T2DM patients
  - Discuss about what figures to include in the main manuscript and supplementary
    - World Health Bulletin
    - Lancet Global Health
  - Should focus more on the diabetes rather than the depression
  - Discuss which journal to submit
  - Results:
    - Create a footnote on the first table: Difference in reanalysis may be due to difference in selection
    - Explaining the meta-regression:
      - Change the reference into Americas (region) and others (instrument)
      - Add the reference to the table
      - Narratively explain how to read the table, give an example
  - Discussion:
    - Potentially need to discuss why the results are different
- Scoping review:
  - Database to use: PsychLit, PsychInfo, PubMed, Scopus, Embase, Web of Science
- Need to converge the methods for all planned studies
- Prepare for 6-month interview, talk about it in the first meeting with Prof. Mako

## 2023-10-12

- Meeting with Prof. Mako: 27 Oct 2023, 16.00 GMT+7 (09.00 GMT+2)
- Create a time table for the discussion with Prof. Mako and Dr. Frederike $\to$ Plan the minutes of meeting
- Propose:
  - Prioritize bibliometrics analysis $\to$ Target: journal submission by December, this will also help my introductory essay
  - Expect delays on analysis of IADB data $\to$ Still need one more week to breakdown the toolbox query, will contact Jens to schedule a meeting tomorrow EOD
  - Scoping review following bibliometrics analysis
- Slide:
  - Speech is ok, but slide is too fast
  - Keep the point you'd like to discuss as the main focus of the slide
- Hanneke from RIVM creates a scoping review on system dynamic model in healthcare $\to$ In the later phase of my scoping review, I should consider having an FGD with RIVM team
- Umbrella review:
  - Preserve the outliers when analyzing the data
  - Create a pairplot and do descriptive analysis from data with preserved outliers:
    - Variables:
      - IV: Prevalence
      - DV: Year of publication, region, and psychometric instrument
  - When fitting metaregression: Set region, year of publication, and psychometric instrument as covariates
  - Consider extracting the dataset and perform clustering analysis

## 2023-10-05

- Umbrella review:
  - Do not remove outliers
  - Use GBD data to calculate the relative risk of having depression in T2DM
  - Complete the data analysis sub-section in the manuscript
  - Storytelling:
    - Do umbrella review on 23 studies $\to$ Fetch all the primary studies
    - Redo meta-analysis, see that the variance is too high
    - We attempted to explain the variance $\to$ Subgroup meta-analysis and meta-regression
    - The heterogeneity is 2% explained by year, meaning that overtime the prevalence of depression is increasing among T2DM patients
    - Interestingly, the GBD data shows that MDD prevalence stays the same while T2DM is increasing overtime
    - The increasing MDD prevalence in T2DM might be explained by T2DM
    - Data from GBD also shows increasing risk of depression in T2DM patients
- IADB:
  - Continue breaking down the source codes
  - Plan a meeting with Talitha and Jens

## 2023-09-29

- Meeting with Prof. Mako should be rescheduled to 20 or 27 October
- Umbrella review:
  - Anomaly detection:
    - Instead of removing the outliers based on 95% CI, it's better to apply outlier detection algorithm
    - Use IQR as a criteria
    - Span the results based on year, do a five-year rolling window
  - Metaregression:
    - Standardize the covariance, they should have the same range
    - Year: Set the smallest value of year as an index year
    - Experimental model: Fit a model without $\beta_0$
    - Addressed concerns:
      - Pooling of proportion from all entries:
        - Do we really want to pool over all studies? That is, do we think we can find a single estimate of the prevalence of MDD in T2DM that would be relevant worldwide and irrespective of outcome or time.
        - Maybe here the proportion as a measure of prevalence differs from an effect measure, where you may reasonably assume it to be independent of setting in principle.
        - Maybe when we combine all the 634 studies, this gives us the global average, which of course reflects a lot of heterogeneity (as we may expres by presenting a histogram). We should then ensure not to take more than one proportion from each study. (so it will be less than 634).
        - Maybe that is more relevant than taking only the studies that are closest together (to avoid heterogeneity). Since we do expect and understand heterogeneity.
      - Subgroup analysis:
        - Do we indeed expect that once we concentrate on country, we can expect to pool? I would be inclined to think so, but as you show, also time, outcome measure and maybe more do matter.
        - So question: Once you stratify by country: can we combine studies into a setting specific average? Is homogeneity sufficient? If not, does it make sense to select studies based on being no outlier? Or would it be more appropriate to further stratify for factors that will explain heterogeneity, like time of study and outcome measure?
      - Next approach to explore:
        - About the pooling. Another factor that could explain heterogeneity is underlying prevalence of MDD and of T2DM.
        - Next to outcome measure, that may also be a matter of risk profile of the population (e.g. obesitas).
        - So could you and Nora also find the expected prevalence (by country/by time), based on published prevalence estimates of MDD and of T2DM (using GBD, WHO, OECD or IHME published numbers, whatever is most clear and consistent); calculate the expected proportion of MDD in T2DM based on such prevalences and then start doing the meta-regression on the remainder (So the additional prevalence of MDD over what you may expect) or maybe on the RR (the crude proportion divided by the expected proportion) or Odds Ratio.
        - Possibly this latter measure is one that you may expect to be the same irrespective of time or setting more reasonably, since it is more of an effect measure (the effect of T2DM on MDD risk). So then it becomes more reasonable to use established methods of meta-regression packages, which were initially developed for pooling effect measures.
        - For the analysis of the observed proportions, I think it is mostly the heterogeneity that you need to show in the results: SO how this varies indeed by country (a map would be great), by outcome measure etc.
        - If you take more than one outcome per study, how could you take account of the dependence these will have? Multilevel analysis an option? Or using clustered standard errors??
  - Analyzing RR:
    - Get the prevalence of MDD in the general population based on year and/or country $\to$ Check GBD or IHME
    - RR = Prevalence of MDD in T2DM, as reported, divided by the prevalence of MDD in the general population
    - Compare the RR for each subgroup
  - Bayesian meta-analysis:
    - Use half-cauchy distribution as a prior for SE
    - Use beta distribution as a prior for the proportion
- IADB:
  - Breakdown the toolbox, check what each lines do
  - Formulate questions to discuss with Jens
- Check courses for meta-regression

## 2023-09-23

- Umbrella review:
  - Might need to redo the analysis
  - To discuss with Katja and Nora:
    - Pros and cons of the current approach
    - Discuss about multiple entries
  - Discuss with Xinyu regarding meta-regression done by the mathematician in RUG:
    - Comparison of methods and packages to conduct metaregression
    - How to handle logit transformation
- IADB data:
  - Recheck the use of persistence toolbox $\to$ Combine parts of the code to my query
  - Change the overlap query into weekly basis
  - Check what we know about concurrent medication uses before and during the pandemic
- Scoping review:
  - Use multiple search to address:
    - Stressors, self perception, and resilience
    - Medication/policy and resilience
    - Resilience and psychological outcomes
  - Check PRISMA guideline on selecting articles for a scoping review
  - Perform bibliometrics analysis to narrow down the search
  - Need to create a clear selection criteria
  - Have a discussion with Frederike Jorg/librarian about the search strategy
  - Check on published articles using scoping review to investigate psychological disorders:
    - https://doi.org/10.1017/S0033291721004177
    - https://doi.org/10.1016/j.pnpbp.2020.110111

## 2023-09-19

- Do monthly meeting with Prof. Talitha and Assoc. Prof. Frederika Jorg on Tuesday/Thursday
- Bimonthly meeting should involve Prof. Mako
- Umbrella review:
  - Create a flow diagram of data management
  - Describe what kind of study is being discarded
  - Merge Korea with South Korea when cleaning the dataset
  - Merge Arab Saudi with Saudi Arabia
  - Merge Maryland with USA
  - In EDA, arrange the self-report instrument together
  - Subgroup analysis for the `incl_year`
  - Search for metaregression for prevalence
  - Share the paper about prediction interval (from meta) and I2 to Prof. Talitha

## 2023-09-07

- Course to take: https://cursus1.webhosting.rug.nl/gsms/course-information/?tx_seminars_pi1%5BshowUid%5D=1675
- IADB data:
  - Need to perform descriptive statistics
  - Tinker the SQL code from IADB toolbox for
- Research proposal:
  - Align the research questions with IADB data request protocol:
    - 1: Add the phrase: "In relation with drug's use"
    - 2: Check the data request protocol
    - 3: How does an individual perceive their health in relation with environmental stressors, such as the COVID-19 pandemic?
  - In scoping review: Include the role of medicine to resilience
  - Find a co-author with primary domain in neuropsychiatry or neurpsychology $\to$ Contact dr. Khamelia
  - Simplify the idea about the model

## 2023-07-20

- Contact Prof. Mako regarding monthly or bi-monthly regular meeting $\to$ Output: Brief MoM
- Protocol draft:
  - Table of population estimate: Check the box to include this data
  - Title: Add in adults
  - Overview of literature: Add other study on the effect of pandemic on the use of psychopharmaca $\to$ Tell how many studies have been done, and how they were investigated
  - In methods: Add comparison during the pandemic because different policy might have different impact $\to$ Add to the exploratory question
  - Clarify the research question, create a footnote to explain what a daily epoch is
  - Specify what the pattern implies in the secondary question
  - Specify "the past five years" as 2018-2022
  - Exclude patients whose prescribed duration is less than two weeks
  - Prescription table: Add variable request for the prescriber
  - Rewrite he effect measures $\to$ Clarify the point in a layman term
  - In statistical methods:
    - First paragraph should be the summary of how I plan my analysis
    - Explain how to analyze the differences before and during COVID-19
    - Link each method with the research questions
    - Add references to the graph knowledge embedding
    - Clarify the aggregation on weekly, monthly, and quarterly basis (first paragraph in methods)
    - Specify what $N$ means $\to$ It is the total number of people making medication claim on daily basis
    - In the fourth paragraph
    - Explain how to handle patients with multiple drugs (use examples, as explained in the email)
    - Use subheadings to clarify which paragraph belongs to which ideas:
      - Executive summary (in bullet point)
      - Data management and feature engineering
      - Concurrent medication use as a matrix
      - Data analysis plan
    - Show the formula for eigenvector centrality $\to$ Refers to the R package being used and its function
    - Explain that the node is the medication
    - Last paragraph: Refer subgroup to the "Stratification of data" section
  - Stratification on age:
    - WHO/ILO: 18-25, 25-35, 35-45, 45-55, >56
    - Theory: 18-25, 25-45, 45-55, >56
  - Report: Interim analysis should be discussed and reported to IADB as well
- Discuss with Nynke Bosman regarding the medication and policy in the Netherlands
- Ask Fang about Dutch's guideline on MDD and anxiety disorder $\to$ Use this as a baseline to select the medication
- There's a table describing zip code into socioeconomic status
- Ask Frederick about courses for time-series analysis

## 2023-07-13

- Complete the data request form by next week
- Draft a SQL query for data request
- Proposal revision:
  - Choice of graph metrics $\to$ Include this as a literature review $\to$ Mention in subsection 4.2
  - Last paragraph in 4.2 is redundant, make it more compact
  - Add about the time-series analysis
  - Clarify the overall purpose: Is it to evaluate seasonality (pattern) or trend?
  - Add about the age range: 18-65
  - In the introduction of 4.2, explain why concurrent drug use is important to evaluate
  - Guideline to use when selecting the medication
- Master's course of time-series analysis in Autumn $\to$ In mathematics and economics department:
  - Mathematics: Fitting dynamical model to data
  - Economics: (Needs further searching)

## 2023-07-06

- Complete the SQL course from IADB, then submit it right away
- Read the book: Going beyond cost-effectiveness by Kaying Kan
- Consider doing:
  - Interrupted time-series analysis
  - Moving average
- List all medications needed  $\to$ Will discuss it later
